// Column detection arrays for bulk product upload
// These arrays contain exhaustive variations of column names to handle different naming conventions

export const NAME_COLUMN_VARIANTS = [

          'Name of Goods', 'name of goods', 'NAME OF GOODS',
          'Name', 'name', 'NAME',
          'Product Name', 'product name', 'PRODUCT NAME',
          'Goods Name', 'goods name', 'GOODS NAME',
          'Item Name', 'item name', 'ITEM NAME',
          'Product', 'product', 'PRODUCT',
          'Title', 'title', 'TITLE',
          'name ', ' Name', ' NAME',
          'product name ', ' Product Name', ' PRODUCT NAME',
          'goods name ', ' Goods Name', ' GOODS NAME',
          'item name ', ' Item Name', ' ITEM NAME',
          'product ', ' Product', ' PRODUCT',
          'title ', ' Title', ' TITLE',
          'Product Title', 'product title', 'PRODUCT TITLE',
          'Item Title', 'item title', 'ITEM TITLE',
          'Goods Title', 'goods title', 'GOODS TITLE',
          'productTitle', 'ProductTitle', 'PRODUCTTITLE',
          'Name of Product', 'name of product', 'NAME OF PRODUCT',
          'Name of Item', 'name of item', 'NAME OF ITEM',
          'Product Label', 'product label', 'PRODUCT LABEL',
          'Item Label', 'item label', 'ITEM LABEL',
          'Designation', 'designation', 'DESIGNATION',
          'Label', 'label', 'LABEL',
          'Tag', 'tag', 'TAG',
          'Identifier', 'identifier', 'IDENTIFIER',
          'ID Name', 'id name', 'ID NAME',
          'Code Name', 'code name', 'CODE NAME',
          'Display Name', 'display name', 'DISPLAY NAME',
          'Display Name', 'displayname', 'DISPLAYNAME',
          'Common Name', 'common name', 'COMMON NAME',
          'Trade Name', 'trade name', 'TRADE NAME',
          'Commercial Name', 'commercial name', 'COMMERCIAL NAME',
          'Market Name', 'market name', 'MARKET NAME',
          'Sales Name', 'sales name', 'SALES NAME',
          'Listing Name', 'listing name', 'LISTING NAME',
          'Catalog Name', 'catalog name', 'CATALOG NAME',
          'Inventory Name', 'inventory name', 'INVENTORY NAME',
          'Stock Name', 'stock name', 'STOCK NAME',
          'Warehouse Name', 'warehouse name', 'WAREHOUSE NAME',
          'Store Name', 'store name', 'STORE NAME',
          'Shop Name', 'shop name', 'SHOP NAME',
          'Retail Name', 'retail name', 'RETAIL NAME',
          'Wholesale Name', 'wholesale name', 'WHOLESALE NAME',
          'Description', 'description', 'DESCRIPTION',
          'Item', 'item', 'ITEM',
          'Good', 'good', 'GOOD',
          'Article', 'article', 'ARTICLE',
          'Material', 'material', 'MATERIAL',
          'Supply', 'supply', 'SUPPLY',
          'Asset', 'asset', 'ASSET',
          'Resource', 'resource', 'RESOURCE',
          'Component', 'component', 'COMPONENT',
          'Part', 'part', 'PART',
          'Unit', 'unit', 'UNIT',
          'Piece', 'piece', 'PIECE',
          'Article Number', 'article number', 'ARTICLE NUMBER',
          'Article No', 'article no', 'ARTICLE NO',
          'Item Number', 'item number', 'ITEM NUMBER',
          'Item No', 'item no', 'ITEM NO',
          'Product Number', 'product number', 'PRODUCT NUMBER',
          'Product No', 'product no', 'PRODUCT NO',
          'Model Name', 'model name', 'MODEL NAME',
          'Model', 'model', 'MODEL',
          'Variant', 'variant', 'VARIANT',
          'Style', 'style', 'STYLE',
          'Type', 'type', 'TYPE',
          'Kind', 'kind', 'KIND',
          'Class', 'class', 'CLASS',
          'Grade', 'grade', 'GRADE',
          'Specification', 'specification', 'SPECIFICATION',
          'Spec', 'spec', 'SPEC',
          'Reference Name', 'reference name', 'REFERENCE NAME',
          'Ref Name', 'ref name', 'REF NAME'
        ,
  // Added from use-case expansions
  'Product Title/Name',
  'Item Name/Title',
  'Good Name',
  'Goods Name/Title',
  'Product/Item Name',
  'Name (English)',
  'Item Description/Name',
  'Article Name',
  'Nomenclature',
  'Item Desc',
  'Product Desc',
  'Primary Name',
  'Goods Description'
];

export const PRICE_COLUMN_VARIANTS = [

          'Price', 'price', 'PRICE',
          'Cost', 'cost', 'COST',
          'Unit Price', 'unit price', 'UNIT PRICE',
          'Amount', 'amount', 'AMOUNT',
          'Rate', 'rate', 'RATE',
          'Selling Price', 'selling price', 'SELLING PRICE',
          'Retail Price', 'retail price', 'RETAIL PRICE',
          'Sales Price', 'sales price', 'SALES PRICE',
          'price ', ' Price', ' PRICE',
          'cost ', ' Cost', ' COST',
          'unitprice', 'UnitPrice', 'UNITPRICE',
          'unit price ', ' Unit Price', ' UNIT PRICE',
          'amount ', ' Amount', ' AMOUNT',
          'rate ', ' Rate', ' RATE',
          'sellingprice', 'Selling Price', 'SELLING PRICE',
          'selling price ', ' Selling Price', ' SELLING PRICE',
          'retailprice', 'Retail Price', 'RETAIL PRICE',
          'retail price ', ' Retail Price', ' RETAIL PRICE',
          'salesprice', 'Sales Price', 'SALES PRICE',
          'sales price ', ' Sales Price', ' SALES PRICE',
          'Unit Cost', 'unit cost', 'UNIT COST',
          'unitcost', 'UnitCost', 'UNITCOST',
          'Item Cost', 'item cost', 'ITEM COST',
          'itemcost', 'ItemCost', 'ITEMCOST',
          'Product Cost', 'product cost', 'PRODUCT COST',
          'productcost', 'ProductCost', 'PRODUCTCOST',
          'Selling Rate', 'selling rate', 'SELLING RATE',
          'sellingrate', 'SellingRate', 'SELLINGRATE',
          'Buying Rate', 'buying rate', 'BUYING RATE',
          'buyingrate', 'BuyingRate', 'BUYINGRATE',
          'Price per Unit', 'price per unit', 'PRICE PER UNIT',
          'pricePerUnit', 'PricePerUnit', 'PRICEPERUNIT',
          'Cost per Unit', 'cost per unit', 'COST PER UNIT',
          'costPerUnit', 'CostPerUnit', 'COSTPERUNIT',
          'Wholesale Price', 'wholesale price', 'WHOLESALE PRICE',
          'wholesaleprice', 'WholesalePrice', 'WHOLESALEPRICE',
          'Base Price', 'base price', 'BASE PRICE',
          'baseprice', 'BasePrice', 'BASEPRICE',
          'Final Price', 'final price', 'FINAL PRICE',
          'finalprice', 'FinalPrice', 'FINALPRICE',
          'Market Price', 'market price', 'MARKET PRICE',
          'marketprice', 'MarketPrice', 'MARKETPRICE',
          'Current Price', 'current price', 'CURRENT PRICE',
          'currentprice', 'CurrentPrice', 'CURRENTPRICE',
          'Net Price', 'net price', 'NET PRICE',
          'netprice', 'NetPrice', 'NETPRICE',
          'Gross Price', 'gross price', 'GROSS PRICE',
          'grossprice', 'GrossPrice', 'GROSSPRICE',
          'Price Point', 'price point', 'PRICE POINT',
          'pricePoint', 'PricePoint', 'PRICEPOINT',
          'Price Tag', 'price tag', 'PRICE TAG',
          'priceTag', 'PriceTag', 'PRICETAG',
          'List Price', 'list price', 'LIST PRICE',
          'listprice', 'ListPrice', 'LISTPRICE',
          'Standard Price', 'standard price', 'STANDARD PRICE',
          'standardprice', 'StandardPrice', 'STANDARDPRICE',
          'Regular Price', 'regular price', 'REGULAR PRICE',
          'regularprice', 'RegularPrice', 'REGULARPRICE',
          'Normal Price', 'normal price', 'NORMAL PRICE',
          'normalprice', 'NormalPrice', 'NORMALPRICE',
          'Actual Price', 'actual price', 'ACTUAL PRICE',
          'actualprice', 'ActualPrice', 'ACTUALPRICE',
          'Effective Price', 'effective price', 'EFFECTIVE PRICE',
          'effectiveprice', 'EffectivePrice', 'EFFECTIVEPRICE',
          'Unit Value', 'unit value', 'UNIT VALUE',
          'unitvalue', 'UnitValue', 'UNITVALUE',
          'Item Value', 'item value', 'ITEM VALUE',
          'itemvalue', 'ItemValue', 'ITEMVALUE',
          'Product Value', 'product value', 'PRODUCT VALUE',
          'productvalue', 'ProductValue', 'PRODUCTVALUE',
          'Worth', 'worth', 'WORTH',
          'Valuation', 'valuation', 'VALUATION',
          'Quote', 'quote', 'QUOTE',
          'Quoted Price', 'quoted price', 'QUOTED PRICE',
          'quotedprice', 'QuotedPrice', 'QUOTEDPRICE',
          'Offer Price', 'offer price', 'OFFER PRICE',
          'offerprice', 'OfferPrice', 'OFFERPRICE',
          'Ask Price', 'ask price', 'ASK PRICE',
          'askprice', 'AskPrice', 'ASKPRICE',
          'Bid Price', 'bid price', 'BID PRICE',
          'bidprice', 'BidPrice', 'BIDPRICE',
          'Trade Price', 'trade price', 'TRADE PRICE',
          'tradeprice', 'TradePrice', 'TRADEPRICE',
          'Exchange Price', 'exchange price', 'EXCHANGE PRICE',
          'exchangeprice', 'ExchangePrice', 'EXCHANGEPRICE',
          'Purchase Price', 'purchase price', 'PURCHASE PRICE',
          'purchaseprice', 'PurchasePrice', 'PURCHASEPRICE',
          'Sale Price', 'sale price', 'SALE PRICE',
          'saleprice', 'SalePrice', 'SALEPRICE',
          'Discounted Price', 'discounted price', 'DISCOUNTED PRICE',
          'discountedprice', 'DiscountedPrice', 'DISCOUNTEDPRICE',
          'Promotional Price', 'promotional price', 'PROMOTIONAL PRICE',
          'promotionalprice', 'PromotionalPrice', 'PROMOTIONALPRICE',
          'Special Price', 'special price', 'SPECIAL PRICE',
          'specialprice', 'SpecialPrice', 'SPECIALPRICE',
          'Deal Price', 'deal price', 'DEAL PRICE',
          'dealprice', 'DealPrice', 'DEALPRICE',
          'Bargain Price', 'bargain price', 'BARGAIN PRICE',
          'bargainprice', 'BargainPrice', 'BARGAINPRICE',
          'Clearance Price', 'clearance price', 'CLEARANCE PRICE',
          'clearanceprice', 'ClearancePrice', 'CLEARANCEPRICE',
          'Liquidation Price', 'liquidation price', 'LIQUIDATION PRICE',
          'liquidationprice', 'LiquidationPrice', 'LIQUIDATIONPRICE',
          'Minimum Price', 'minimum price', 'MINIMUM PRICE',
          'minimumprice', 'MinimumPrice', 'MINIMUMPRICE',
          'Maximum Price', 'maximum price', 'MAXIMUM PRICE',
          'maximumprice', 'MaximumPrice', 'MAXIMUMPRICE',
          'Floor Price', 'floor price', 'FLOOR PRICE',
          'floorprice', 'FloorPrice', 'FLOORPRICE',
          'Ceiling Price', 'ceiling price', 'CEILING PRICE',
          'ceilingprice', 'CeilingPrice', 'CEILINGPRICE',
          'Target Price', 'target price', 'TARGET PRICE',
          'targetprice', 'TargetPrice', 'TARGETPRICE',
          'Budget Price', 'budget price', 'BUDGET PRICE',
          'budgetprice', 'BudgetPrice', 'BUDGETPRICE',
          'Estimated Price', 'estimated price', 'ESTIMATED PRICE',
          'estimatedprice', 'EstimatedPrice', 'ESTIMATEDPRICE',
          'Projected Price', 'projected price', 'PROJECTED PRICE',
          'projectedprice', 'ProjectedPrice', 'PROJECTEDPRICE',
          'Expected Price', 'expected price', 'EXPECTED PRICE',
          'expectedprice', 'ExpectedPrice', 'EXPECTEDPRICE',
          'Planned Price', 'planned price', 'PLANNED PRICE',
          'plannedprice', 'PlannedPrice', 'PLANNEDPRICE',
          'Proposed Price', 'proposed price', 'PROPOSED PRICE',
          'proposedprice', 'ProposedPrice', 'PROPOSEDPRICE',
          'Suggested Price', 'suggested price', 'SUGGESTED PRICE',
          'suggestedprice', 'SuggestedPrice', 'SUGGESTEDPRICE',
          'Recommended Price', 'recommended price', 'RECOMMENDED PRICE',
          'recommendedprice', 'RecommendedPrice', 'RECOMMENDEDPRICE',
          'Advertised Price', 'advertised price', 'ADVERTISED PRICE',
          'advertisedprice', 'AdvertisedPrice', 'ADVERTISEDPRICE',
          'Listed Price', 'listed price', 'LISTED PRICE',
          'listedprice', 'ListedPrice', 'LISTEDPRICE',
          'Posted Price', 'posted price', 'POSTED PRICE',
          'postedprice', 'PostedPrice', 'POSTEDPRICE',
          'Displayed Price', 'displayed price', 'DISPLAYED PRICE',
          'displayedprice', 'DisplayedPrice', 'DISPLAYEDPRICE',
          'Shown Price', 'shown price', 'SHOWN PRICE',
          'shownprice', 'ShownPrice', 'SHOWNPRICE',
          'Marked Price', 'marked price', 'MARKED PRICE',
          'markedprice', 'MarkedPrice', 'MARKEDPRICE',
          'Tagged Price', 'tagged price', 'TAGGED PRICE',
          'taggedprice', 'TaggedPrice', 'TAGGEDPRICE',
          'Sticker Price', 'sticker price', 'STICKER PRICE',
          'stickerprice', 'StickerPrice', 'STICKERPRICE',
          'Label Price', 'label price', 'LABEL PRICE',
          'labelprice', 'LabelPrice', 'LABELPRICE'
        ,
  // Added from use-case expansions
  'Price (NGN)',
  'Price(Naira)',
  'Price (₦)',
  'Selling Price (N)',
  'Unit Price (NGN)',
  'Cost (NGN)',
  'Amount (NGN)',
  'Retail Price (NGN)',
  'Price ($)',
  'Unit Price ($)',
  'Current Selling Price',
  'Final Selling Price',
  'Selling Price (₦)',
  'Price/Unit',
  'Item Price (NGN)'
];

export const COMPARE_PRICE_COLUMN_VARIANTS = [

          'Compare Price', 'compare price', 'COMPARE PRICE',
          'comparePrice', 'ComparePrice', 'COMPAREPRICE',
          'Original Price', 'original price', 'ORIGINAL PRICE',
          'originalPrice', 'OriginalPrice', 'ORIGINALPRICE',
          'List Price', 'list price', 'LIST PRICE',
          'listPrice', 'ListPrice', 'LISTPRICE',
          'MRP', 'mrp', 'M.R.P.',
          'MSRP', 'msrp', 'M.S.R.P.',
          'compare price ', ' Compare Price', ' COMPARE PRICE',
          'original price ', ' Original Price', ' ORIGINAL PRICE',
          'list price ', ' List Price', ' LIST PRICE',
          'Compare at', 'compare at', 'COMPARE AT',
          'compareAt', 'CompareAt', 'COMPAREAT',
          'Was Price', 'was price', 'WAS PRICE',
          'wasPrice', 'WasPrice', 'WASPRICE',
          'Before Price', 'before price', 'BEFORE PRICE',
          'beforePrice', 'BeforePrice', 'BEFOREPRICE',
          'Old Price', 'old price', 'OLD PRICE',
          'oldPrice', 'OldPrice', 'OLDPRICE',
          'Previous Price', 'previous price', 'PREVIOUS PRICE',
          'previousPrice', 'PreviousPrice', 'PREVIOUSPRICE',
          'Regular Price', 'regular price', 'REGULAR PRICE',
          'regularPrice', 'RegularPrice', 'REGULARPRICE',
          'Standard Price', 'standard price', 'STANDARD PRICE',
          'standardPrice', 'StandardPrice', 'STANDARDPRICE',
          'Normal Price', 'normal price', 'NORMAL PRICE',
          'normalPrice', 'NormalPrice', 'NORMALPRICE',
          'Reference Price', 'reference price', 'REFERENCE PRICE',
          'referencePrice', 'ReferencePrice', 'REFERENCEPRICE',
          'Base Price', 'base price', 'BASE PRICE',
          'basePrice', 'BasePrice', 'BASEPRICE',
          'Retail Price', 'retail price', 'RETAIL PRICE',
          'retailPrice', 'RetailPrice', 'RETAILPRICE',
          'Wholesale Price', 'wholesale price', 'WHOLESALE PRICE',
          'wholesalePrice', 'WholesalePrice', 'WHOLESALEPRICE',
          'Manufacturer Price', 'manufacturer price', 'MANUFACTURER PRICE',
          'manufacturerPrice', 'ManufacturerPrice', 'MANUFACTURERPRICE',
          'Supplier Price', 'supplier price', 'SUPPLIER PRICE',
          'supplierPrice', 'SupplierPrice', 'SUPPLIERPRICE',
          'Vendor Price', 'vendor price', 'VENDOR PRICE',
          'vendorPrice', 'VendorPrice', 'VENDORPRICE',
          'Suggested Retail Price', 'suggested retail price', 'SUGGESTED RETAIL PRICE',
          'suggestedRetailPrice', 'SuggestedRetailPrice', 'SUGGESTEDRETAILPRICE',
          'SRP', 'srp', 'S.R.P.',
          'Recommended Price', 'recommended price', 'RECOMMENDED PRICE',
          'recommendedPrice', 'RecommendedPrice', 'RECOMMENDEDP RICE',
          'Advertised Price', 'advertised price', 'ADVERTISED PRICE',
          'advertisedPrice', 'AdvertisedPrice', 'ADVERTISEDP RICE',
          'Ticket Price', 'ticket price', 'TICKET PRICE',
          'ticketPrice', 'TicketPrice', 'TICKETPRICE',
          'Sticker Price', 'sticker price', 'STICKER PRICE',
          'stickerPrice', 'StickerPrice', 'STICKERPRICE',
          'Marked Price', 'marked price', 'MARKED PRICE',
          'markedPrice', 'MarkedPrice', 'MARKEDPRICE',
          'Tag Price', 'tag price', 'TAG PRICE',
          'tagPrice', 'TagPrice', 'TAGPRICE',
          'Label Price', 'label price', 'LABEL PRICE',
          'labelPrice', 'LabelPrice', 'LABELPRICE',
          'Catalog Price', 'catalog price', 'CATALOG PRICE',
          'catalogPrice', 'CatalogPrice', 'CATALOGPRICE',
          'Book Price', 'book price', 'BOOK PRICE',
          'bookPrice', 'BookPrice', 'BOOKPRICE',
          'Listed Price', 'listed price', 'LISTED PRICE',
          'listedPrice', 'ListedPrice', 'LISTEDPRICE',
          'Posted Price', 'posted price', 'POSTED PRICE',
          'postedPrice', 'PostedPrice', 'POSTEDPRICE',
          'Displayed Price', 'displayed price', 'DISPLAYED PRICE',
          'displayedPrice', 'DisplayedPrice', 'DISPLAYEDPRICE',
          'Shown Price', 'shown price', 'SHOWN PRICE',
          'shownPrice', 'ShownPrice', 'SHOWNPRICE',
          'Crossed Price', 'crossed price', 'CROSSED PRICE',
          'crossedPrice', 'CrossedPrice', 'CROSSEDPRICE',
          'Strikethrough Price', 'strikethrough price', 'STRIKETHROUGH PRICE',
          'strikethroughPrice', 'StrikethroughPrice', 'STRIKETHROUGHPRICE',
          'Strike Price', 'strike price', 'STRIKE PRICE',
          'strikePrice', 'StrikePrice', 'STRIKEPRICE',
          'Discount Price', 'discount price', 'DISCOUNT PRICE',
          'discountPrice', 'DiscountPrice', 'DISCOUNTPRICE',
          'Full Price', 'full price', 'FULL PRICE',
          'fullPrice', 'FullPrice', 'FULLPRICE',
          'Complete Price', 'complete price', 'COMPLETE PRICE',
          'completePrice', 'CompletePrice', 'COMPLETEPRICE',
          'Total Price', 'total price', 'TOTAL PRICE',
          'totalPrice', 'TotalPrice', 'TOTALPRICE',
          'Gross Price', 'gross price', 'GROSS PRICE',
          'grossPrice', 'GrossPrice', 'GROSSPRICE',
          'Net Price', 'net price', 'NET PRICE',
          'netPrice', 'NetPrice', 'NETPRICE',
          'Unit Price', 'unit price', 'UNIT PRICE',
          'unitPrice', 'UnitPrice', 'UNITPRICE',
          'Per Unit Price', 'per unit price', 'PER UNIT PRICE',
          'perUnitPrice', 'PerUnitPrice', 'PERUNITPRICE',
          'Price per Item', 'price per item', 'PRICE PER ITEM',
          'pricePerItem', 'PricePerItem', 'PRICEPERITEM',
          'Item Price', 'item price', 'ITEM PRICE',
          'itemPrice', 'ItemPrice', 'ITEMPRICE',
          'Piece Price', 'piece price', 'PIECE PRICE',
          'piecePrice', 'PiecePrice', 'PIECEPRICE',
          'Each Price', 'each price', 'EACH PRICE',
          'eachPrice', 'EachPrice', 'EACHPRICE'
        ,
  // Added from use-case expansions
  'Old Price (NGN)',
  'MSRP ($)',
  'RRP',
  'Recommended Retail Price',
  'Compare At Price',
  'Original Price (NGN)',
  'Old Price (₦)',
  'List Price (NGN)',
  'Was',
  'Previous Price (NGN)'
];

export const STOCK_COLUMN_VARIANTS = [

          'Stock', 'stock', 'STOCK',
          'Quantity', 'quantity', 'QUANTITY',
          'Qty', 'qty', 'QTY',
          'Inventory', 'inventory', 'INVENTORY',
          'Available', 'available', 'AVAILABLE',
          'In Stock', 'in stock', 'IN STOCK',
          'instock', 'InStock', 'INSTOCK',
          'stock ', ' Stock', ' STOCK',
          'quantity ', ' Quantity', ' QUANTITY',
          'qty ', ' Qty', ' QTY',
          'inventory ', ' Inventory', ' INVENTORY',
          'available ', ' Available', ' AVAILABLE',
          'on hand', 'On Hand', 'ON HAND',
          'onhand', 'OnHand', 'ONHAND',
          'stock level', 'Stock Level', 'STOCK LEVEL',
          'stocklevel', 'StockLevel', 'STOCKLEVEL',
          'Stock Count', 'stock count', 'STOCK COUNT',
          'stockCount', 'StockCount', 'STOCKCOUNT',
          'Stock Quantity', 'stock quantity', 'STOCK QUANTITY',
          'stockQuantity', 'StockQuantity', 'STOCKQUANTITY',
          'Available Stock', 'available stock', 'AVAILABLE STOCK',
          'availableStock', 'AvailableStock', 'AVAILABLESTOCK',
          'Current Stock', 'current stock', 'CURRENT STOCK',
          'currentStock', 'CurrentStock', 'CURRENTSTOCK',
          'Stock on Hand', 'stock on hand', 'STOCK ON HAND',
          'stockOnHand', 'StockOnHand', 'STOCKONHAND',
          'Stock in Hand', 'stock in hand', 'STOCK IN HAND',
          'stockInHand', 'StockInHand', 'STOCKINHAND',
          'Inventory Count', 'inventory count', 'INVENTORY COUNT',
          'inventoryCount', 'InventoryCount', 'INVENTORYCOUNT',
          'Inventory Level', 'inventory level', 'INVENTORY LEVEL',
          'inventoryLevel', 'InventoryLevel', 'INVENTORYLEVEL',
          'Inventory Quantity', 'inventory quantity', 'INVENTORY QUANTITY',
          'inventoryQuantity', 'InventoryQuantity', 'INVENTORYQUANTITY',
          'Quantity in Stock', 'quantity in stock', 'QUANTITY IN STOCK',
          'quantityInStock', 'QuantityInStock', 'QUANTITYINSTOCK',
          'Qty in Stock', 'qty in stock', 'QTY IN STOCK',
          'qtyInStock', 'QtyInStock', 'QTYINSTOCK',
          'Units Available', 'units available', 'UNITS AVAILABLE',
          'unitsAvailable', 'UnitsAvailable', 'UNITSAVAILABLE',
          'Units in Stock', 'units in stock', 'UNITS IN STOCK',
          'unitsInStock', 'UnitsInStock', 'UNITSINSTOCK',
          'Stock Balance', 'stock balance', 'STOCK BALANCE',
          'stockBalance', 'StockBalance', 'STOCKBALANCE',
          'Stock Amount', 'stock amount', 'STOCK AMOUNT',
          'stockAmount', 'StockAmount', 'STOCKAMOUNT',
          'Warehouse Stock', 'warehouse stock', 'WAREHOUSE STOCK',
          'warehouseStock', 'WarehouseStock', 'WAREHOUSESTOCK',
          'Store Stock', 'store stock', 'STORE STOCK',
          'storeStock', 'StoreStock', 'STORESTOCK',
          'Shop Stock', 'shop stock', 'SHOP STOCK',
          'shopStock', 'ShopStock', 'SHOPSTOCK',
          'Retail Stock', 'retail stock', 'RETAIL STOCK',
          'retailStock', 'RetailStock', 'RETAILSTOCK',
          'Wholesale Stock', 'wholesale stock', 'WHOLESALE STOCK',
          'wholesaleStock', 'WholesaleStock', 'WHOLESALESTOCK',
          'Physical Stock', 'physical stock', 'PHYSICAL STOCK',
          'physicalStock', 'PhysicalStock', 'PHYSICALSTOCK',
          'Actual Stock', 'actual stock', 'ACTUAL STOCK',
          'actualStock', 'ActualStock', 'ACTUALSTOCK',
          'Real Stock', 'real stock', 'REAL STOCK',
          'realStock', 'RealStock', 'REALSTOCK',
          'Total Stock', 'total stock', 'TOTAL STOCK',
          'totalStock', 'TotalStock', 'TOTALSTOCK',
          'Net Stock', 'net stock', 'NET STOCK',
          'netStock', 'NetStock', 'NETSTOCK',
          'Gross Stock', 'gross stock', 'GROSS STOCK',
          'grossStock', 'GrossStock', 'GROSSSTOCK',
          'Opening Stock', 'opening stock', 'OPENING STOCK',
          'openingStock', 'OpeningStock', 'OPENINGSTOCK',
          'Closing Stock', 'closing stock', 'CLOSING STOCK',
          'closingStock', 'ClosingStock', 'CLOSINGSTOCK',
          'Beginning Stock', 'beginning stock', 'BEGINNING STOCK',
          'beginningStock', 'BeginningStock', 'BEGINNINGSTOCK',
          'Ending Stock', 'ending stock', 'ENDING STOCK',
          'endingStock', 'EndingStock', 'ENDINGSTOCK',
          'Start Stock', 'start stock', 'START STOCK',
          'startStock', 'StartStock', 'STARTSTOCK',
          'End Stock', 'end stock', 'END STOCK',
          'endStock', 'EndStock', 'ENDSTOCK',
          'Initial Stock', 'initial stock', 'INITIAL STOCK',
          'initialStock', 'InitialStock', 'INITIALSTOCK',
          'Final Stock', 'final stock', 'FINAL STOCK',
          'finalStock', 'FinalStock', 'FINALSTOCK',
          'Minimum Stock', 'minimum stock', 'MINIMUM STOCK',
          'minimumStock', 'MinimumStock', 'MINIMUMSTOCK',
          'Maximum Stock', 'maximum stock', 'MAXIMUM STOCK',
          'maximumStock', 'MaximumStock', 'MAXIMUMSTOCK',
          'Reorder Stock', 'reorder stock', 'REORDER STOCK',
          'reorderStock', 'ReorderStock', 'REORDERSTOCK',
          'Safety Stock', 'safety stock', 'SAFETY STOCK',
          'safetyStock', 'SafetyStock', 'SAFETYSTOCK',
          'Buffer Stock', 'buffer stock', 'BUFFER STOCK',
          'bufferStock', 'BufferStock', 'BUFFERSTOCK',
          'Reserve Stock', 'reserve stock', 'RESERVE STOCK',
          'reserveStock', 'ReserveStock', 'RESERVESTOCK',
          'Reserved Stock', 'reserved stock', 'RESERVED STOCK',
          'reservedStock', 'ReservedStock', 'RESERVEDSTOCK',
          'Allocated Stock', 'allocated stock', 'ALLOCATED STOCK',
          'allocatedStock', 'AllocatedStock', 'ALLOCATEDSTOCK',
          'Committed Stock', 'committed stock', 'COMMITTED STOCK',
          'committedStock', 'CommittedStock', 'COMMITTEDSTOCK',
          'Free Stock', 'free stock', 'FREE STOCK',
          'freeStock', 'FreeStock', 'FREESTOCK',
          'Unallocated Stock', 'unallocated stock', 'UNALLOCATED STOCK',
          'unallocatedStock', 'UnallocatedStock', 'UNALLOCATEDSTOCK',
          'Uncommitted Stock', 'uncommitted stock', 'UNCOMMITTED STOCK',
          'uncommittedStock', 'UncommittedStock', 'UNCOMMITTEDSTOCK',
          'Available Quantity', 'available quantity', 'AVAILABLE QUANTITY',
          'availableQuantity', 'AvailableQuantity', 'AVAILABLEQUANTITY',
          'On Hand Quantity', 'on hand quantity', 'ON HAND QUANTITY',
          'onHandQuantity', 'OnHandQuantity', 'ONHANDQUANTITY',
          'In Store', 'in store', 'IN STORE',
          'inStore', 'InStore', 'INSTORE',
          'In Warehouse', 'in warehouse', 'IN WAREHOUSE',
          'inWarehouse', 'InWarehouse', 'INWAREHOUSE',
          'On Shelf', 'on shelf', 'ON SHELF',
          'onShelf', 'OnShelf', 'ONSHELF',
          'On Floor', 'on floor', 'ON FLOOR',
          'onFloor', 'OnFloor', 'ONFLOOR',
          'Stock Position', 'stock position', 'STOCK POSITION',
          'stockPosition', 'StockPosition', 'STOCKPOSITION',
          'Stock Status', 'stock status', 'STOCK STATUS',
          'stockStatus', 'StockStatus', 'STOCKSTATUS',
          'Stock Condition', 'stock condition', 'STOCK CONDITION',
          'stockCondition', 'StockCondition', 'STOCKCONDITION',
          'Stock Availability', 'stock availability', 'STOCK AVAILABILITY',
          'stockAvailability', 'StockAvailability', 'STOCKAVAILABILITY',
          'Availability Status', 'availability status', 'AVAILABILITY STATUS',
          'availabilityStatus', 'AvailabilityStatus', 'AVAILABILITYSTATUS',
          'Count', 'count', 'COUNT',
          'Number', 'number', 'NUMBER',
          'Amount', 'amount', 'AMOUNT',
          'Total', 'total', 'TOTAL',
          'Balance', 'balance', 'BALANCE',
          'Remaining', 'remaining', 'REMAINING',
          'Left', 'left', 'LEFT',
          'Remainder', 'remainder', 'REMAINDER',
          'Residue', 'residue', 'RESIDUE',
          'Surplus', 'surplus', 'SURPLUS',
          'Excess', 'excess', 'EXCESS',
          'Deficit', 'deficit', 'DEFICIT',
          'Shortage', 'shortage', 'SHORTAGE',
          'Backorder', 'backorder', 'BACKORDER',
          'Back Order', 'back order', 'BACK ORDER',
          'backOrder', 'BackOrder', 'BACKORDER',
          'Out of Stock', 'out of stock', 'OUT OF STOCK',
          'outOfStock', 'OutOfStock', 'OUTOFSTOCK',
          'OOS', 'oos', 'O.O.S.',
          'Stock Out', 'stock out', 'STOCK OUT',
          'stockOut', 'StockOut', 'STOCKOUT',
          'Stock Short', 'stock short', 'STOCK SHORT',
          'stockShort', 'StockShort', 'STOCKSHORT',
          'Low Stock', 'low stock', 'LOW STOCK',
          'lowStock', 'LowStock', 'LOWSTOCK',
          'Critical Stock', 'critical stock', 'CRITICAL STOCK',
          'criticalStock', 'CriticalStock', 'CRITICALSTOCK',
          'Overstock', 'overstock', 'OVERSTOCK',
          'Over Stock', 'over stock', 'OVER STOCK',
          'overStock', 'OverStock', 'OVERSTOCK',
          'Excess Stock', 'excess stock', 'EXCESS STOCK',
          'excessStock', 'ExcessStock', 'EXCESSSTOCK'
        ,
  // Added from use-case expansions
  'Qty Available',
  'SOH',
  'Stock On Hand',
  'Stock (Qty)',
  'Inventory (Qty)',
  'Available Qty',
  'Total Qty',
  'Units',
  'Available Units',
  'Current Inventory',
  'Stock Level (Qty)'
];

export const BRAND_COLUMN_VARIANTS = [

          'Brand', 'brand', 'BRAND',
          'Manufacturer', 'manufacturer', 'MANUFACTURER',
          'Make', 'make', 'MAKE',
          'Vendor', 'vendor', 'VENDOR',
          'Supplier', 'supplier', 'SUPPLIER',
          'brand ', ' Brand', ' BRAND',
          'manufacturer ', ' Manufacturer', ' MANUFACTURER',
          'make ', ' Make', ' MAKE',
          'vendor ', ' Vendor', ' VENDOR',
          'supplier ', ' Supplier', ' SUPPLIER',
          'company', 'Company', 'COMPANY',
          'producer', 'Producer', 'PRODUCER',
          'creator', 'Creator', 'CREATOR',
          'maker', 'Maker', 'MAKER',
          'builder', 'Builder', 'BUILDER',
          'fabricator', 'Fabricator', 'FABRICATOR',
          'origin', 'Origin', 'ORIGIN',
          'source', 'Source', 'SOURCE',
          'country of origin', 'Country of Origin', 'COUNTRY OF ORIGIN',
          'countryOfOrigin', 'CountryOfOrigin', 'COUNTRYOFORIGIN',
          'made by', 'Made By', 'MADE BY',
          'madeBy', 'MadeBy', 'MADEBY',
          'produced by', 'Produced By', 'PRODUCED BY',
          'producedBy', 'ProducedBy', 'PRODUCEDBY',
          'manufactured by', 'Manufactured By', 'MANUFACTURED BY',
          'manufacturedBy', 'ManufacturedBy', 'MANUFACTUREDBY',
          'built by', 'Built By', 'BUILT BY',
          'builtBy', 'BuiltBy', 'BUILDBY',
          'assembled by', 'Assembled By', 'ASSEMBLED BY',
          'assembledBy', 'AssembledBy', 'ASSEMBLEDBY',
          'brand name', 'Brand Name', 'BRAND NAME',
          'brandName', 'BrandName', 'BRANDNAME',
          'manufacturer name', 'Manufacturer Name', 'MANUFACTURER NAME',
          'manufacturerName', 'ManufacturerName', 'MANUFACTURERNAME',
          'company name', 'Company Name', 'COMPANY NAME',
          'companyName', 'CompanyName', 'COMPANYNAME',
          'firm name', 'Firm Name', 'FIRM NAME',
          'firmName', 'FirmName', 'FIRMNAME',
          'organization', 'Organization', 'ORGANIZATION',
          'org', 'Org', 'ORG',
          'business', 'Business', 'BUSINESS',
          'enterprise', 'Enterprise', 'ENTERPRISE',
          'corporation', 'Corporation', 'CORPORATION',
          'corp', 'Corp', 'CORP',
          'inc', 'Inc', 'INC',
          'ltd', 'Ltd', 'LTD',
          'llc', 'LLC', 'LLC',
          'trademark', 'Trademark', 'TRADEMARK',
          'trade mark', 'Trade Mark', 'TRADE MARK',
          'tradeMark', 'TradeMark', 'TRADEMARK',
          'label', 'Label', 'LABEL',
          'mark', 'Mark', 'MARK',
          'badge', 'Badge', 'BADGE',
          'logo', 'Logo', 'LOGO',
          'emblem', 'Emblem', 'EMBLEM',
          'symbol', 'Symbol', 'SYMBOL',
          'signature', 'Signature', 'SIGNATURE',
          'stamp', 'Stamp', 'STAMP',
          'seal', 'Seal', 'SEAL',
          'tag', 'Tag', 'TAG',
          'tagline', 'Tagline', 'TAGLINE',
          'slogan', 'Slogan', 'SLOGAN',
          'motto', 'Motto', 'MOTTO',
          'branding', 'Branding', 'BRANDING',
          'identity', 'Identity', 'IDENTITY',
          'style', 'Style', 'STYLE',
          'line', 'Line', 'LINE',
          'series', 'Series', 'SERIES',
          'collection', 'Collection', 'COLLECTION',
          'range', 'Range', 'RANGE',
          'family', 'Family', 'FAMILY',
          'group', 'Group', 'GROUP',
          'division', 'Division', 'DIVISION',
          'department', 'Department', 'DEPARTMENT',
          'subsidiary', 'Subsidiary', 'SUBSIDIARY',
          'parent company', 'Parent Company', 'PARENT COMPANY',
          'parentCompany', 'ParentCompany', 'PARENTCOMPANY',
          'owner', 'Owner', 'OWNER',
          'proprietor', 'Proprietor', 'PROPRIETOR',
          'founder', 'Founder', 'FOUNDER',
          'creator', 'Creator', 'CREATOR',
          'inventor', 'Inventor', 'INVENTOR',
          'designer', 'Designer', 'DESIGNER',
          'developer', 'Developer', 'DEVELOPER',
          'publisher', 'Publisher', 'PUBLISHER',
          'distributor', 'Distributor', 'DISTRIBUTOR',
          'retailer', 'Retailer', 'RETAILER',
          'wholesaler', 'Wholesaler', 'WHOLESALER',
          'dealer', 'Dealer', 'DEALER',
          'reseller', 'Reseller', 'RESELLER',
          'merchant', 'Merchant', 'MERCHANT',
          'trader', 'Trader', 'TRADER',
          'seller', 'Seller', 'SELLER',
          'provider', 'Provider', 'PROVIDER',
          'service provider', 'Service Provider', 'SERVICE PROVIDER',
          'serviceProvider', 'ServiceProvider', 'SERVICEPROVIDER',
          'contractor', 'Contractor', 'CONTRACTOR',
          'partner', 'Partner', 'PARTNER',
          'affiliate', 'Affiliate', 'AFFILIATE',
          'associate', 'Associate', 'ASSOCIATE',
          'collaborator', 'Collaborator', 'COLLABORATOR',
          'licensor', 'Licensor', 'LICENSOR',
          'licensee', 'Licensee', 'LICENSEE',
          'franchise', 'Franchise', 'FRANCHISE',
          'franchisee', 'Franchisee', 'FRANCHISEE',
          'franchisor', 'Franchisor', 'FRANCHISOR',
          'brand owner', 'Brand Owner', 'BRAND OWNER',
          'brandOwner', 'BrandOwner', 'BRANDOWNER',
          'trademark owner', 'Trademark Owner', 'TRADEMARK OWNER',
          'trademarkOwner', 'TrademarkOwner', 'TRADEMARKOWNER',
          'copyright holder', 'Copyright Holder', 'COPYRIGHT HOLDER',
          'copyrightHolder', 'CopyrightHolder', 'COPYRIGHTHOLDER',
          'patent holder', 'Patent Holder', 'PATENT HOLDER',
          'patentHolder', 'PatentHolder', 'PATENTHOLDER',
          'rights holder', 'Rights Holder', 'RIGHTS HOLDER',
          'rightsHolder', 'RightsHolder', 'RIGHTSHOLDER',
          'intellectual property', 'Intellectual Property', 'INTELLECTUAL PROPERTY',
          'intellectualProperty', 'IntellectualProperty', 'INTELLECTUALPROPERTY',
          'IP', 'ip', 'I.P.',
          'brand equity', 'Brand Equity', 'BRAND EQUITY',
          'brandEquity', 'BrandEquity', 'BRANDEQUITY',
          'brand value', 'Brand Value', 'BRAND VALUE',
          'brandValue', 'BrandValue', 'BRANDVALUE',
          'brand recognition', 'Brand Recognition', 'BRAND RECOGNITION',
          'brandRecognition', 'BrandRecognition', 'BRANDRECOGNITION',
          'brand awareness', 'Brand Awareness', 'BRAND AWARENESS',
          'brandAwareness', 'BrandAwareness', 'BRANDAWARENESS',
          'market position', 'Market Position', 'MARKET POSITION',
          'marketPosition', 'MarketPosition', 'MARKETPOSITION',
          'market share', 'Market Share', 'MARKET SHARE',
          'marketShare', 'MarketShare', 'MARKETSHARE',
          'industry', 'Industry', 'INDUSTRY',
          'sector', 'Sector', 'SECTOR',
          'niche', 'Niche', 'NICHE',
          'segment', 'Segment', 'SEGMENT',
          'category', 'Category', 'CATEGORY',
          'class', 'Class', 'CLASS',
          'grade', 'Grade', 'GRADE',
          'quality', 'Quality', 'QUALITY',
          'standard', 'Standard', 'STANDARD',
          'specification', 'Specification', 'SPECIFICATION',
          'certification', 'Certification', 'CERTIFICATION',
          'accreditation', 'Accreditation', 'ACCREDITATION',
          'approval', 'Approval', 'APPROVAL',
          'endorsement', 'Endorsement', 'ENDORSEMENT',
          'recommendation', 'Recommendation', 'RECOMMENDATION',
          'rating', 'Rating', 'RATING',
          'review', 'Review', 'REVIEW',
          'feedback', 'Feedback', 'FEEDBACK',
          'testimonial', 'Testimonial', 'TESTIMONIAL',
          'reference', 'Reference', 'REFERENCE',
          'referral', 'Referral', 'REFERRAL',
          'citation', 'Citation', 'CITATION',
          'mention', 'Mention', 'MENTION',
          'attribution', 'Attribution', 'ATTRIBUTION',
          'credit', 'Credit', 'CREDIT',
          'acknowledgment', 'Acknowledgment', 'ACKNOWLEDGMENT',
          'acknowledgement', 'Acknowledgement', 'ACKNOWLEDGEMENT'
        ,
  // Added from use-case expansions
  'Mfg',
  'Manufacturer Name',
  'Brand/Manufacturer',
  'Brand Name/Mfg',
  'Make/Brand',
  'Brand (OEM)',
  'OEM',
  'Vendor Name',
  'Supplier Name'
];

export const SKU_COLUMN_VARIANTS = [

          'SKU', 'sku', 'Sku',
          'Stock Keeping Unit', 'stock keeping unit', 'STOCK KEEPING UNIT',
          'Item Code', 'item code', 'ITEM CODE',
          'itemCode', 'ItemCode', 'ITEMCODE',
          'Product Code', 'product code', 'PRODUCT CODE',
          'productCode', 'ProductCode', 'PRODUCTCODE',
          'Part Number', 'part number', 'PART NUMBER',
          'partNumber', 'PartNumber', 'PARTNUMBER',
          'Reference', 'reference', 'REFERENCE',
          'sku ', ' SKU', ' Sku',
          'item code ', ' Item Code', ' ITEM CODE',
          'product code ', ' Product Code', ' PRODUCT CODE',
          'part number ', ' Part Number', ' PART NUMBER',
          'SKU Number', 'sku number', 'SKU NUMBER',
          'skuNumber', 'SkuNumber', 'SKUNUMBER',
          'SKU Code', 'sku code', 'SKU CODE',
          'skuCode', 'SkuCode', 'SKUCODE',
          'Stock Code', 'stock code', 'STOCK CODE',
          'stockCode', 'StockCode', 'STOCKCODE',
          'Item Number', 'item number', 'ITEM NUMBER',
          'itemNumber', 'ItemNumber', 'ITEMNUMBER',
          'Item No', 'item no', 'ITEM NO',
          'itemNo', 'ItemNo', 'ITEMNO',
          'Product Number', 'product number', 'PRODUCT NUMBER',
          'productNumber', 'ProductNumber', 'PRODUCTNUMBER',
          'Product No', 'product no', 'PRODUCT NO',
          'productNo', 'ProductNo', 'PRODUCTNO',
          'Inventory Code', 'inventory code', 'INVENTORY CODE',
          'inventoryCode', 'InventoryCode', 'INVENTORYCODE',
          'Stock Number', 'stock number', 'STOCK NUMBER',
          'stockNumber', 'StockNumber', 'STOCKNUMBER',
          'Stock No', 'stock no', 'STOCK NO',
          'stockNo', 'StockNo', 'STOCKNO',
          'Bar Code', 'bar code', 'BAR CODE',
          'barCode', 'BarCode', 'BARCODE',
          'Barcode', 'barcode', 'BARCODE',
          'UPC', 'upc', 'U.P.C.',
          'EAN', 'ean', 'E.A.N.',
          'ISBN', 'isbn', 'I.S.B.N.',
          'Serial Number', 'serial number', 'SERIAL NUMBER',
          'serialNumber', 'SerialNumber', 'SERIALNUMBER',
          'Serial No', 'serial no', 'SERIAL NO',
          'serialNo', 'SerialNo', 'SERIALNO',
          'Model Number', 'model number', 'MODEL NUMBER',
          'modelNumber', 'ModelNumber', 'MODELNUMBER',
          'Model No', 'model no', 'MODEL NO',
          'modelNo', 'ModelNo', 'MODELNO',
          'Model Code', 'model code', 'MODEL CODE',
          'modelCode', 'ModelCode', 'MODELCODE',
          'Catalog Number', 'catalog number', 'CATALOG NUMBER',
          'catalogNumber', 'CatalogNumber', 'CATALOGNUMBER',
          'Catalog No', 'catalog no', 'CATALOG NO',
          'catalogNo', 'CatalogNo', 'CATALOGNO',
          'Catalog Code', 'catalog code', 'CATALOG CODE',
          'catalogCode', 'CatalogCode', 'CATALOGCODE',
          'Reference Number', 'reference number', 'REFERENCE NUMBER',
          'referenceNumber', 'ReferenceNumber', 'REFERENCENUMBER',
          'Reference No', 'reference no', 'REFERENCE NO',
          'referenceNo', 'ReferenceNo', 'REFERENCENO',
          'ID', 'id', 'ID',
          'Identifier', 'identifier', 'IDENTIFIER',
          'Identification', 'identification', 'IDENTIFICATION',
          'Identification Number', 'identification number', 'IDENTIFICATION NUMBER',
          'identificationNumber', 'IdentificationNumber', 'IDENTIFICATIONNUMBER',
          'Identification Code', 'identification code', 'IDENTIFICATION CODE',
          'identificationCode', 'IdentificationCode', 'IDENTIFICATIONCODE',
          'Product ID', 'product id', 'PRODUCT ID',
          'productId', 'ProductId', 'PRODUCTID',
          'Product SKU', 'product sku', 'PRODUCT SKU',
          'productSku', 'ProductSku', 'PRODUCTSKU',
          'Item SKU', 'item sku', 'ITEM SKU',
          'itemSku', 'ItemSku', 'ITEMSKU',
          'Goods SKU', 'goods sku', 'GOODS SKU',
          'goodsSku', 'GoodsSku', 'GOODSSKU',
          'Material Code', 'material code', 'MATERIAL CODE',
          'materialCode', 'MaterialCode', 'MATERIALCODE',
          'Material Number', 'material number', 'MATERIAL NUMBER',
          'materialNumber', 'MaterialNumber', 'MATERIALNUMBER',
          'Asset Code', 'asset code', 'ASSET CODE',
          'assetCode', 'AssetCode', 'ASSETCODE',
          'Asset Number', 'asset number', 'ASSET NUMBER',
          'assetNumber', 'AssetNumber', 'ASSETNUMBER',
          'Equipment Code', 'equipment code', 'EQUIPMENT CODE',
          'equipmentCode', 'EquipmentCode', 'EQUIPMENTCODE',
          'Equipment Number', 'equipment number', 'EQUIPMENT NUMBER',
          'equipmentNumber', 'EquipmentNumber', 'EQUIPMENTNUMBER',
          'Tool Code', 'tool code', 'TOOL CODE',
          'toolCode', 'ToolCode', 'TOOLCODE',
          'Tool Number', 'tool number', 'TOOL NUMBER',
          'toolNumber', 'ToolNumber', 'TOOLNUMBER',
          'Component Code', 'component code', 'COMPONENT CODE',
          'componentCode', 'ComponentCode', 'COMPONENTCODE',
          'Component Number', 'component number', 'COMPONENT NUMBER',
          'componentNumber', 'ComponentNumber', 'COMPONENTNUMBER',
          'Part Code', 'part code', 'PART CODE',
          'partCode', 'PartCode', 'PARTCODE',
          'Assembly Code', 'assembly code', 'ASSEMBLY CODE',
          'assemblyCode', 'AssemblyCode', 'ASSEMBLYCODE',
          'Assembly Number', 'assembly number', 'ASSEMBLY NUMBER',
          'assemblyNumber', 'AssemblyNumber', 'ASSEMBLYNUMBER',
          'Unit Code', 'unit code', 'UNIT CODE',
          'unitCode', 'UnitCode', 'UNITCODE',
          'Unit Number', 'unit number', 'UNIT NUMBER',
          'unitNumber', 'UnitNumber', 'UNITNUMBER',
          'Piece Code', 'piece code', 'PIECE CODE',
          'pieceCode', 'PieceCode', 'PIECECODE',
          'Piece Number', 'piece number', 'PIECE NUMBER',
          'pieceNumber', 'PieceNumber', 'PIECENUMBER',
          'Batch Number', 'batch number', 'BATCH NUMBER',
          'batchNumber', 'BatchNumber', 'BATCHNUMBER',
          'Batch Code', 'batch code', 'BATCH CODE',
          'batchCode', 'BatchCode', 'BATCHCODE',
          'Lot Number', 'lot number', 'LOT NUMBER',
          'lotNumber', 'LotNumber', 'LOTNUMBER',
          'Lot Code', 'lot code', 'LOT CODE',
          'lotCode', 'LotCode', 'LOTCODE',
          'Run Number', 'run number', 'RUN NUMBER',
          'runNumber', 'RunNumber', 'RUNNUMBER',
          'Job Number', 'job number', 'JOB NUMBER',
          'jobNumber', 'JobNumber', 'JOBNUMBER',
          'Order Number', 'order number', 'ORDER NUMBER',
          'orderNumber', 'OrderNumber', 'ORDERNUMBER',
          'PO Number', 'po number', 'PO NUMBER',
          'poNumber', 'PoNumber', 'PONUMBER',
          'Purchase Order', 'purchase order', 'PURCHASE ORDER',
          'purchaseOrder', 'PurchaseOrder', 'PURCHASEORDER',
          'Sales Order', 'sales order', 'SALES ORDER',
          'salesOrder', 'SalesOrder', 'SALESORDER',
          'Invoice Number', 'invoice number', 'INVOICE NUMBER',
          'invoiceNumber', 'InvoiceNumber', 'INVOICENUMBER',
          'Bill Number', 'bill number', 'BILL NUMBER',
          'billNumber', 'BillNumber', 'BILLNUMBER',
          'Receipt Number', 'receipt number', 'RECEIPT NUMBER',
          'receiptNumber', 'ReceiptNumber', 'RECEIPTNUMBER',
          'Ticket Number', 'ticket number', 'TICKET NUMBER',
          'ticketNumber', 'TicketNumber', 'TICKETNUMBER',
          'Voucher Number', 'voucher number', 'VOUCHER NUMBER',
          'voucherNumber', 'VoucherNumber', 'VOUCHERNUMBER',
          'Coupon Code', 'coupon code', 'COUPON CODE',
          'couponCode', 'CouponCode', 'COUPONCODE',
          'Promo Code', 'promo code', 'PROMO CODE',
          'promoCode', 'PromoCode', 'PROMOCODE',
          'Discount Code', 'discount code', 'DISCOUNT CODE',
          'discountCode', 'DiscountCode', 'DISCOUNTCODE',
          'Access Code', 'access code', 'ACCESS CODE',
          'accessCode', 'AccessCode', 'ACCESSCODE',
          'Security Code', 'security code', 'SECURITY CODE',
          'securityCode', 'SecurityCode', 'SECURITYCODE',
          'Auth Code', 'auth code', 'AUTH CODE',
          'authCode', 'AuthCode', 'AUTHCODE',
          'Token', 'token', 'TOKEN',
          'Key', 'key', 'KEY',
          'Password', 'password', 'PASSWORD',
          'PIN', 'pin', 'P.I.N.',
          'OTP', 'otp', 'O.T.P.',
          'Verification Code', 'verification code', 'VERIFICATION CODE',
          'verificationCode', 'VerificationCode', 'VERIFICATIONCODE',
          'Confirmation Code', 'confirmation code', 'CONFIRMATION CODE',
          'confirmationCode', 'ConfirmationCode', 'CONFIRMATIONCODE',
          'Tracking Number', 'tracking number', 'TRACKING NUMBER',
          'trackingNumber', 'TrackingNumber', 'TRACKINGNUMBER',
          'Tracking Code', 'tracking code', 'TRACKING CODE',
          'trackingCode', 'TrackingCode', 'TRACKINGCODE',
          'Shipment Number', 'shipment number', 'SHIPMENT NUMBER',
          'shipmentNumber', 'ShipmentNumber', 'SHIPMENTNUMBER',
          'Delivery Number', 'delivery number', 'DELIVERY NUMBER',
          'deliveryNumber', 'DeliveryNumber', 'DELIVERYNUMBER',
          'Package Number', 'package number', 'PACKAGE NUMBER',
          'packageNumber', 'PackageNumber', 'PACKAGENUMBER',
          'Container Number', 'container number', 'CONTAINER NUMBER',
          'containerNumber', 'ContainerNumber', 'CONTAINERNUMBER',
          'Pallet Number', 'pallet number', 'PALLET NUMBER',
          'palletNumber', 'PalletNumber', 'PALLETNUMBER',
          'Box Number', 'box number', 'BOX NUMBER',
          'boxNumber', 'BoxNumber', 'BOXNUMBER',
          'Carton Number', 'carton number', 'CARTON NUMBER',
          'cartonNumber', 'CartonNumber', 'CARTONNUMBER',
          'Case Number', 'case number', 'CASE NUMBER',
          'caseNumber', 'CaseNumber', 'CASENUMBER',
          'Pack Number', 'pack number', 'PACK NUMBER',
          'packNumber', 'PackNumber', 'PACKNUMBER',
          'Bundle Number', 'bundle number', 'BUNDLE NUMBER',
          'bundleNumber', 'BundleNumber', 'BUNDLENUMBER',
          'Set Number', 'set number', 'SET NUMBER',
          'setNumber', 'SetNumber', 'SETNUMBER',
          'Kit Number', 'kit number', 'KIT NUMBER',
          'kitNumber', 'KitNumber', 'KITNUMBER',
          'Group Number', 'group number', 'GROUP NUMBER',
          'groupNumber', 'GroupNumber', 'GROUPNUMBER',
          'Series Number', 'series number', 'SERIES NUMBER',
          'seriesNumber', 'SeriesNumber', 'SERIESNUMBER',
          'Version Number', 'version number', 'VERSION NUMBER',
          'versionNumber', 'VersionNumber', 'VERSIONNUMBER',
          'Revision Number', 'revision number', 'REVISION NUMBER',
          'revisionNumber', 'RevisionNumber', 'REVISIONNUMBER',
          'Edition Number', 'edition number', 'EDITION NUMBER',
          'editionNumber', 'EditionNumber', 'EDITIONNUMBER',
          'Release Number', 'release number', 'RELEASE NUMBER',
          'releaseNumber', 'ReleaseNumber', 'RELEASENUMBER',
          'Build Number', 'build number', 'BUILD NUMBER',
          'buildNumber', 'BuildNumber', 'BUILDNUMBER',
          'Version Code', 'version code', 'VERSION CODE',
          'versionCode', 'VersionCode', 'VERSIONCODE',
          'Revision Code', 'revision code', 'REVISION CODE',
          'revisionCode', 'RevisionCode', 'REVISIONCODE',
          'Edition Code', 'edition code', 'EDITION CODE',
          'editionCode', 'EditionCode', 'EDITIONCODE',
          'Release Code', 'release code', 'RELEASE CODE',
          'releaseCode', 'ReleaseCode', 'RELEASECODE',
          'Build Code', 'build code', 'BUILD CODE',
          'buildCode', 'BuildCode', 'BUILDCODE',
          'Code', 'code', 'CODE',
          'No', 'no', 'NO',
          'Num', 'num', 'NUM',
          'Ref', 'ref', 'REF',
          'Tag', 'tag', 'TAG',
          'Label', 'label', 'LABEL',
          'Mark', 'mark', 'MARK',
          'Stamp', 'stamp', 'STAMP',
          'Seal', 'seal', 'SEAL',
          'Badge', 'badge', 'BADGE',
          'Sticker', 'sticker', 'STICKER',
          'Label', 'label', 'LABEL'
        ,
  // Added from use-case expansions
  'Item #',
  'Part #',
  'SKU ID',
  'SKU No.',
  'Item No.',
  'Product #',
  'SKU/Item Number',
  'Stock Keeping Unit (SKU)',
  'Unique ID',
  'Product Code/SKU',
  'Internal SKU',
  'Store SKU'
];

export const DESCRIPTION_COLUMN_VARIANTS = [

          'Description', 'description', 'DESCRIPTION',
          'Desc', 'desc', 'DESC',
          'Details', 'details', 'DETAILS',
          'Notes', 'notes', 'NOTES',
          'Product Description', 'product description', 'PRODUCT DESCRIPTION',
          'productDescription', 'ProductDescription', 'PRODUCTDESCRIPTION',
          'Item Description', 'item description', 'ITEM DESCRIPTION',
          'itemDescription', 'ItemDescription', 'ITEMDESCRIPTION',
          'description ', ' Description', ' DESCRIPTION',
          'desc ', ' Desc', ' DESC',
          'details ', ' Details', ' DETAILS',
          'notes ', ' Notes', ' NOTES',
          'specifications', 'Specifications', 'SPECIFICATIONS',
          'specs', 'Specs', 'SPECS',
          'features', 'Features', 'FEATURES',
          'about', 'About', 'ABOUT'
        ,
  // Added from use-case expansions
  'Full Description',
  'Long Description',
  'Item Detailed Description',
  'Product Details/Description',
  'Detailed Description',
  'Main Description',
  'Desc (Long)'
];

export const CATEGORY_ID_COLUMN_VARIANTS = [

          'Category ID', 'category id', 'CATEGORY ID',
          'CategoryId', 'categoryId', 'CATEGORYID',
          'Category_Id', 'category_id', 'CATEGORY_ID',
          'Category', 'category', 'CATEGORY',
          'Cat ID', 'cat id', 'CAT ID',
          'CatId', 'catId', 'CATID',
          'category id ', ' Category ID', ' CATEGORY ID',
          'category_id ', ' Category_Id', ' CATEGORY_ID',
          'category ', ' Category', ' CATEGORY',
          'cat id ', ' Cat ID', ' CAT ID',
          'section', 'Section', 'SECTION',
          'group', 'Group', 'GROUP',
          'type', 'Type', 'TYPE'
        ,
  // Added from use-case expansions
  'Category Level 1',
  'Product Type',
  'Taxonomy',
  'Category Name',
  'Primary Category',
  'Department',
  'Cat',
  'Cat ID',
  'Sub-Category',
  'Subcategory',
  'Product Category'
];

export const SHORT_DESCRIPTION_COLUMN_VARIANTS = [

          'Short Description', 'short description', 'SHORT DESCRIPTION',
          'shortDescription', 'ShortDescription', 'SHORTDESCRIPTION',
          'Summary', 'summary', 'SUMMARY',
          'Brief Description', 'brief description', 'BRIEF DESCRIPTION',
          'briefDescription', 'BriefDescription', 'BRIEFDESCRIPTION',
          'Overview', 'overview', 'OVERVIEW',
          'Teaser', 'teaser', 'TEASER',
          'short description ', ' Short Description', ' SHORT DESCRIPTION',
          'summary ', ' Summary', ' SUMMARY',
          'brief description ', ' Brief Description', ' BRIEF DESCRIPTION',
          'overview ', ' Overview', ' OVERVIEW',
          'excerpt', 'Excerpt', 'EXCERPT',
          'snippet', 'Snippet', 'SNIPPET'
        ,
  // Added from use-case expansions
  'Teaser Text',
  'Brief',
  'Short Desc',
  'Summary/Short Description',
  'Desc (Short)',
  'Mini Description',
  'Highlight',
  'Key Features'
];

export const STATUS_COLUMN_VARIANTS = [

          'Status', 'status', 'STATUS',
          'State', 'state', 'STATE',
          'Condition', 'condition', 'CONDITION',
          'Availability', 'availability', 'AVAILABILITY',
          'status ', ' Status', ' STATUS',
          'state ', ' State', ' STATE',
          'condition ', ' Condition', ' CONDITION',
          'availability ', ' Availability', ' AVAILABILITY',
          'active', 'Active', 'ACTIVE',
          'inactive', 'Inactive', 'INACTIVE',
          'enabled', 'Enabled', 'ENABLED',
          'disabled', 'Disabled', 'DISABLED'
        ,
  // Added from use-case expansions
  'Item Status',
  'Is Active',
  'Product Status',
  'Visibility',
  'Active/Inactive',
  'Status (Active/Inactive)',
  'Current Status',
  'Lifecycle Status'
];

export const FEATURED_COLUMN_VARIANTS = [

          'Featured', 'featured', 'FEATURED',
          'Is Featured', 'is featured', 'IS FEATURED',
          'isFeatured', 'IsFeatured', 'ISFEATURED',
          'Highlight', 'highlight', 'HIGHLIGHT',
          'Featured Item', 'featured item', 'FEATURED ITEM',
          'featuredItem', 'FeaturedItem', 'FEATUREDITEM',
          'featured ', ' Featured', ' FEATURED',
          'is featured ', ' Is Featured', ' IS FEATURED',
          'highlight ', ' Highlight', ' HIGHLIGHT',
          'featured item ', ' Featured Item', ' FEATURED ITEM',
          'starred', 'Starred', 'STARRED',
          'promoted', 'Promoted', 'PROMOTED',
          'recommended', 'Recommended', 'RECOMMENDED'
        ,
  // Added from use-case expansions
  'Is Promoted',
  'Home Page Featured',
  'Featured Product',
  'Is Highlighted',
  'Promoted',
  'Top Product',
  'Show on Homepage',
  'Star Product'
];

export const LOW_STOCK_THRESHOLD_COLUMN_VARIANTS = [

          'Low Stock Threshold', 'low stock threshold', 'LOW STOCK THRESHOLD',
          'lowStockThreshold', 'LowStockThreshold', 'LOWSTOCKTHRESHOLD',
          'Reorder Level', 'reorder level', 'REORDER LEVEL',
          'reorderLevel', 'ReorderLevel', 'REORDERLEVEL',
          'Min Stock', 'min stock', 'MIN STOCK',
          'minStock', 'MinStock', 'MINSTOCK',
          'Minimum Stock', 'minimum stock', 'MINIMUM STOCK',
          'minimumStock', 'MinimumStock', 'MINIMUMSTOCK',
          'Reorder Point', 'reorder point', 'REORDER POINT',
          'reorderPoint', 'ReorderPoint', 'REORDERPOINT',
          'low stock threshold ', ' Low Stock Threshold', ' LOW STOCK THRESHOLD',
          'reorder level ', ' Reorder Level', ' REORDER LEVEL',
          'min stock ', ' Min Stock', ' MIN STOCK',
          'minimum stock ', ' Minimum Stock', ' MINIMUM STOCK',
          'reorder point ', ' Reorder Point', ' REORDER POINT',
          'stock alert', 'Stock Alert', 'STOCK ALERT',
          'stockAlert', 'StockAlert', 'STOCKALERT',
          'alert level', 'Alert Level', 'ALERT LEVEL',
          'alertLevel', 'AlertLevel', 'ALERTLEVEL'
        ,
  // Added from use-case expansions
  'Alert Threshold',
  'Re-order Point',
  'Min Qty',
  'Minimum Order Quantity',
  'Safety Stock Level',
  'Low Inventory Alert',
  'Restock Level',
  'Warning Level'
];

