// Column detection arrays for bulk product upload
// These arrays contain exhaustive variations of column names to handle different naming conventions

export const NAME_COLUMN_VARIANTS = [
  'name of goods',
  'name',
  'product name',
  'goods name',
  'item name',
  'product',
  'title',
  'product title',
  'item title',
  'goods title',
  'producttitle',
  'name of product',
  'name of item',
  'product label',
  'item label',
  'designation',
  'label',
  'tag',
  'identifier',
  'id name',
  'code name',
  'display name',
  'displayname',
  'common name',
  'trade name',
  'commercial name',
  'market name',
  'sales name',
  'listing name',
  'catalog name',
  'inventory name',
  'stock name',
  'warehouse name',
  'store name',
  'shop name',
  'retail name',
  'wholesale name',
  'item',
  'good',
  'article',
  'material',
  'supply',
  'asset',
  'resource',
  'component',
  'part',
  'unit',
  'piece',
  'article number',
  'article no',
  'item number',
  'item no',
  'product number',
  'product no',
  'model name',
  'model',
  'variant',
  'style',
  'type',
  'kind',
  'class',
  'grade',
  'specification',
  'spec',
  'reference name',
  'ref name',
  // Added from use-case expansions
  'product title/name',
  'item name/title',
  'good name',
  'goods name/title',
  'product/item name',
  'name (english)',
  'item description/name',
  'article name',
  'nomenclature',
  'item desc',
  'product desc',
  'primary name',
  'goods description'
];

export const PRICE_COLUMN_VARIANTS = [
  'price',
  'cost',
  'unit price',
  'amount',
  'rate',
  'selling price',
  'retail price',
  'sales price',
  'unitprice',
  'unit cost',
  'item cost',
  'itemcost',
  'product cost',
  'productcost',
  'selling rate',
  'sellingrate',
  'buying rate',
  'buyingrate',
  'price per unit',
  'priceperunit',
  'cost per unit',
  'costperunit',
  'wholesale price',
  'wholesaleprice',
  'base price',
  'baseprice',
  'final price',
  'finalprice',
  'market price',
  'marketprice',
  'current price',
  'currentprice',
  'net price',
  'netprice',
  'gross price',
  'grossprice',
  'price point',
  'pricepoint',
  'price tag',
  'pricetag',
  'list price',
  'listprice',
  'standard price',
  'standardprice',
  'regular price',
  'regularprice',
  'normal price',
  'normalprice',
  'actual price',
  'actualprice',
  'effective price',
  'effectiveprice',
  'unit value',
  'unitvalue',
  'item value',
  'itemvalue',
  'product value',
  'productvalue',
  'worth',
  'valuation',
  'quote',
  'quoted price',
  'quotedprice',
  'offer price',
  'offerprice',
  'ask price',
  'askprice',
  'bid price',
  'bidprice',
  'trade price',
  'tradeprice',
  'exchange price',
  'exchangeprice',
  'purchase price',
  'purchaseprice',
  'sale price',
  'saleprice',
  'discounted price',
  'discountedprice',
  'promotional price',
  'promotionalprice',
  'special price',
  'specialprice',
  'deal price',
  'dealprice',
  'bargain price',
  'bargainprice',
  'clearance price',
  'clearanceprice',
  'liquidation price',
  'liquidationprice',
  'minimum price',
  'minimumprice',
  'maximum price',
  'maximumprice',
  'floor price',
  'floorprice',
  'ceiling price',
  'ceilingprice',
  'target price',
  'targetprice',
  'budget price',
  'budgetprice',
  'estimated price',
  'estimatedprice',
  'projected price',
  'projectedprice',
  'expected price',
  'expectedprice',
  'planned price',
  'plannedprice',
  'proposed price',
  'proposedprice',
  'suggested price',
  'suggestedprice',
  'recommended price',
  'recommendedprice',
  'advertised price',
  'advertisedprice',
  'listed price',
  'listedprice',
  'posted price',
  'postedprice',
  'displayed price',
  'displayedprice',
  'shown price',
  'shownprice',
  'marked price',
  'markedprice',
  'tagged price',
  'taggedprice',
  'sticker price',
  'stickerprice',
  'label price',
  'labelprice',
  // Added from use-case expansions
  'price (ngn)',
  'price(naira)',
  'price (₦)',
  'selling price (n)',
  'unit price (ngn)',
  'cost (ngn)',
  'amount (ngn)',
  'retail price (ngn)',
  'price ($)',
  'unit price ($)',
  'current selling price',
  'final selling price',
  'selling price (₦)',
  'price/unit',
  'item price (ngn)'
];

export const COMPARE_PRICE_COLUMN_VARIANTS = [
  'compare price',
  'compareprice',
  'original price',
  'originalprice',
  'list price',
  'listprice',
  'mrp',
  'msrp',
  'compare at',
  'compareat',
  'was price',
  'wasprice',
  'before price',
  'beforeprice',
  'old price',
  'oldprice',
  'previous price',
  'previousprice',
  'regular price',
  'regularprice',
  'standard price',
  'standardprice',
  'normal price',
  'normalprice',
  'reference price',
  'referenceprice',
  'base price',
  'baseprice',
  'retail price',
  'retailprice',
  'wholesale price',
  'wholesaleprice',
  'manufacturer price',
  'manufacturerprice',
  'supplier price',
  'supplierprice',
  'vendor price',
  'vendorprice',
  'suggested retail price',
  'suggestedretailprice',
  'srp',
  'recommended price',
  'recommendedprice',
  'advertised price',
  'advertisedprice',
  'ticket price',
  'ticketprice',
  'sticker price',
  'stickerprice',
  'marked price',
  'markedprice',
  'tag price',
  'tagprice',
  'label price',
  'labelprice',
  'catalog price',
  'catalogprice',
  'book price',
  'bookprice',
  'listed price',
  'listedprice',
  'posted price',
  'postedprice',
  'displayed price',
  'displayedprice',
  'shown price',
  'shownprice',
  'crossed price',
  'crossedprice',
  'strikethrough price',
  'strikethroughprice',
  'strike price',
  'strikeprice',
  'discount price',
  'discountprice',
  'full price',
  'fullprice',
  'complete price',
  'completeprice',
  'total price',
  'totalprice',
  'gross price',
  'grossprice',
  'net price',
  'netprice',
  'unit price',
  'unitprice',
  'per unit price',
  'perunitprice',
  'price per item',
  'priceperitem',
  'item price',
  'itemprice',
  'piece price',
  'pieceprice',
  'each price',
  'eachprice',
  // Added from use-case expansions
  'old price (ngn)',
  'msrp ($)',
  'rrp',
  'recommended retail price',
  'compare at price',
  'original price (ngn)',
  'old price (₦)',
  'list price (ngn)',
  'was',
  'previous price (ngn)'
];

export const STOCK_COLUMN_VARIANTS = [
  'stock',
  'quantity',
  'qty',
  'inventory',
  'available',
  'in stock',
  'instock',
  'on hand',
  'onhand',
  'stock level',
  'stocklevel',
  'stock count',
  'stockcount',
  'stock quantity',
  'stockquantity',
  'available stock',
  'availablestock',
  'current stock',
  'currentstock',
  'stock on hand',
  'stockonhand',
  'stock in hand',
  'stockinhand',
  'inventory count',
  'inventorycount',
  'inventory level',
  'inventorylevel',
  'inventory quantity',
  'inventoryquantity',
  'quantity in stock',
  'quantityinstock',
  'qty in stock',
  'qtyinstock',
  'units available',
  'unitsavailable',
  'units in stock',
  'unitsinstock',
  'stock balance',
  'stockbalance',
  'stock amount',
  'stockamount',
  'warehouse stock',
  'warehousestock',
  'store stock',
  'storestock',
  'shop stock',
  'shopstock',
  'retail stock',
  'retailstock',
  'wholesale stock',
  'wholesalestock',
  'physical stock',
  'physicalstock',
  'actual stock',
  'actualstock',
  'real stock',
  'realstock',
  'total stock',
  'totalstock',
  'net stock',
  'netstock',
  'gross stock',
  'grossstock',
  'opening stock',
  'openingstock',
  'closing stock',
  'closingstock',
  'beginning stock',
  'beginningstock',
  'ending stock',
  'endingstock',
  'start stock',
  'startstock',
  'end stock',
  'endstock',
  'initial stock',
  'initialstock',
  'final stock',
  'finalstock',
  'minimum stock',
  'minimumstock',
  'maximum stock',
  'maximumstock',
  'reorder stock',
  'reorderstock',
  'safety stock',
  'safetystock',
  'buffer stock',
  'bufferstock',
  'reserve stock',
  'reservestock',
  'reserved stock',
  'reservedstock',
  'allocated stock',
  'allocatedstock',
  'committed stock',
  'committedstock',
  'free stock',
  'freestock',
  'unallocated stock',
  'unallocatedstock',
  'uncommitted stock',
  'uncommittedstock',
  'available quantity',
  'availablequantity',
  'on hand quantity',
  'onhandquantity',
  'in store',
  'instore',
  'in warehouse',
  'inwarehouse',
  'on shelf',
  'onshelf',
  'on floor',
  'onfloor',
  'stock position',
  'stockposition',
  'stock status',
  'stockstatus',
  'stock condition',
  'stockcondition',
  'stock availability',
  'stockavailability',
  'availability status',
  'availabilitystatus',
  'count',
  'number',
  'amount',
  'total',
  'balance',
  'remaining',
  'left',
  'remainder',
  'residue',
  'surplus',
  'excess',
  'deficit',
  'shortage',
  'backorder',
  'back order',
  'backorder',
  'out of stock',
  'outofstock',
  'oos',
  'stock out',
  'stockout',
  'stock short',
  'stockshort',
  'low stock',
  'lowstock',
  'critical stock',
  'criticalstock',
  'overstock',
  'over stock',
  'overstock',
  'excess stock',
  'excessstock',
  // Added from use-case expansions
  'qty available',
  'soh',
  'stock on hand',
  'stock (qty)',
  'inventory (qty)',
  'available qty',
  'total qty',
  'units',
  'available units',
  'current inventory',
  'stock level (qty)'
];

export const BRAND_COLUMN_VARIANTS = [
  'brand',
  'manufacturer',
  'make',
  'vendor',
  'supplier',
  'company',
  'producer',
  'creator',
  'maker',
  'builder',
  'fabricator',
  'origin',
  'source',
  'country of origin',
  'countryoforigin',
  'made by',
  'madeby',
  'produced by',
  'producedby',
  'manufactured by',
  'manufacturedby',
  'built by',
  'builtby',
  'assembled by',
  'assembledby',
  'brand name',
  'brandname',
  'manufacturer name',
  'manufacturername',
  'company name',
  'companyname',
  'firm name',
  'firmname',
  'organization',
  'org',
  'business',
  'enterprise',
  'corporation',
  'corp',
  'inc',
  'ltd',
  'llc',
  'trademark',
  'trade mark',
  'trademark',
  'label',
  'mark',
  'badge',
  'logo',
  'emblem',
  'symbol',
  'signature',
  'stamp',
  'seal',
  'tag',
  'tagline',
  'slogan',
  'motto',
  'branding',
  'identity',
  'style',
  'line',
  'series',
  'collection',
  'range',
  'family',
  'group',
  'division',
  'department',
  'subsidiary',
  'parent company',
  'parentcompany',
  'owner',
  'proprietor',
  'founder',
  'creator',
  'inventor',
  'designer',
  'developer',
  'publisher',
  'distributor',
  'retailer',
  'wholesaler',
  'dealer',
  'reseller',
  'merchant',
  'trader',
  'seller',
  'provider',
  'service provider',
  'serviceprovider',
  'contractor',
  'partner',
  'affiliate',
  'associate',
  'collaborator',
  'licensor',
  'licensee',
  'franchise',
  'franchisee',
  'franchisor',
  'brand owner',
  'brandowner',
  'trademark owner',
  'trademarkowner',
  'copyright holder',
  'copyrightholder',
  'patent holder',
  'patentholder',
  'rights holder',
  'rightsholder',
  'intellectual property',
  'intellectualproperty',
  'ip',
  'brand equity',
  'brandequity',
  'brand value',
  'brandvalue',
  'brand recognition',
  'brandrecognition',
  'brand awareness',
  'brandawareness',
  'market position',
  'marketposition',
  'market share',
  'marketshare',
  'industry',
  'sector',
  'niche',
  'segment',
  'category',
  'class',
  'grade',
  'quality',
  'standard',
  'specification',
  'certification',
  'accreditation',
  'approval',
  'endorsement',
  'recommendation',
  'rating',
  'review',
  'feedback',
  'testimonial',
  'reference',
  'referral',
  'citation',
  'mention',
  'attribution',
  'credit',
  'acknowledgment',
  'acknowledgement',
  // Added from use-case expansions
  'mfg',
  'manufacturer name',
  'brand/manufacturer',
  'brand name/mfg',
  'make/brand',
  'brand (oem)',
  'oem',
  'vendor name',
  'supplier name'
];

export const SKU_COLUMN_VARIANTS = [
  'sku',
  'stock keeping unit',
  'item code',
  'itemcode',
  'product code',
  'productcode',
  'part number',
  'partnumber',
  'reference',
  'sku number',
  'skunumber',
  'sku code',
  'skucode',
  'stock code',
  'stockcode',
  'item number',
  'itemnumber',
  'item no',
  'itemno',
  'product number',
  'productnumber',
  'product no',
  'productno',
  'inventory code',
  'inventorycode',
  'stock number',
  'stocknumber',
  'stock no',
  'stockno',
  'bar code',
  'barcode',
  'barcode',
  'upc',
  'ean',
  'isbn',
  'serial number',
  'serialnumber',
  'serial no',
  'serialno',
  'model number',
  'modelnumber',
  'model no',
  'modelno',
  'model code',
  'modelcode',
  'catalog number',
  'catalognumber',
  'catalog no',
  'catalogno',
  'catalog code',
  'catalogcode',
  'reference number',
  'referencenumber',
  'reference no',
  'referenceno',
  'id',
  'identifier',
  'identification',
  'identification number',
  'identificationnumber',
  'identification code',
  'identificationcode',
  'product id',
  'productid',
  'product sku',
  'productsku',
  'item sku',
  'itemsku',
  'goods sku',
  'goodssku',
  'material code',
  'materialcode',
  'material number',
  'materialnumber',
  'asset code',
  'assetcode',
  'asset number',
  'assetnumber',
  'equipment code',
  'equipmentcode',
  'equipment number',
  'equipmentnumber',
  'tool code',
  'toolcode',
  'tool number',
  'toolnumber',
  'component code',
  'componentcode',
  'component number',
  'componentnumber',
  'part code',
  'partcode',
  'assembly code',
  'assemblycode',
  'assembly number',
  'assemblynumber',
  'unit code',
  'unitcode',
  'unit number',
  'unitnumber',
  'piece code',
  'piececode',
  'piece number',
  'piecenumber',
  'batch number',
  'batchnumber',
  'batch code',
  'batchcode',
  'lot number',
  'lotnumber',
  'lot code',
  'lotcode',
  'run number',
  'runnumber',
  'job number',
  'jobnumber',
  'order number',
  'ordernumber',
  'po number',
  'ponumber',
  'purchase order',
  'purchaseorder',
  'sales order',
  'salesorder',
  'invoice number',
  'invoicenumber',
  'bill number',
  'billnumber',
  'receipt number',
  'receiptnumber',
  'ticket number',
  'ticketnumber',
  'voucher number',
  'vouchernumber',
  'coupon code',
  'couponcode',
  'promo code',
  'promocode',
  'discount code',
  'discountcode',
  'access code',
  'accesscode',
  'security code',
  'securitycode',
  'auth code',
  'authcode',
  'token',
  'key',
  'password',
  'pin',
  'otp',
  'verification code',
  'verificationcode',
  'confirmation code',
  'confirmationcode',
  'tracking number',
  'trackingnumber',
  'tracking code',
  'trackingcode',
  'shipment number',
  'shipmentnumber',
  'delivery number',
  'deliverynumber',
  'package number',
  'packagenumber',
  'container number',
  'containernumber',
  'pallet number',
  'palletnumber',
  'box number',
  'boxnumber',
  'carton number',
  'cartonnumber',
  'case number',
  'casenumber',
  'pack number',
  'packnumber',
  'bundle number',
  'bundlenumber',
  'set number',
  'setnumber',
  'kit number',
  'kitnumber',
  'group number',
  'groupnumber',
  'series number',
  'seriesnumber',
  'version number',
  'versionnumber',
  'revision number',
  'revisionnumber',
  'edition number',
  'editionnumber',
  'release number',
  'releasenumber',
  'build number',
  'buildnumber',
  'version code',
  'versioncode',
  'revision code',
  'revisioncode',
  'edition code',
  'editioncode',
  'release code',
  'releasecode',
  'build code',
  'buildcode',
  'code',
  'no',
  'num',
  'ref',
  'tag',
  'label',
  'mark',
  'stamp',
  'seal',
  'badge',
  'sticker',
  // Added from use-case expansions
  'item #',
  'part #',
  'sku id',
  'sku no.',
  'item no.',
  'product #',
  'sku/item number',
  'stock keeping unit (sku)',
  'unique id',
  'product code/sku',
  'internal sku',
  'store sku'
];

export const DESCRIPTION_COLUMN_VARIANTS = [
  'description',
  'desc',
  'details',
  'notes',
  'product description',
  'productdescription',
  'item description',
  'itemdescription',
  'specifications',
  'specs',
  'features',
  'about',
  // Added from use-case expansions
  'full description',
  'long description',
  'item detailed description',
  'product details/description',
  'detailed description',
  'main description',
  'desc (long)'
];

export const CATEGORY_ID_COLUMN_VARIANTS = [
  'category id',
  'categoryid',
  'category_id',
  'category',
  'cat id',
  'catid',
  'section',
  'group',
  'type',
  // Added from use-case expansions
  'category level 1',
  'product type',
  'taxonomy',
  'category name',
  'primary category',
  'department',
  'cat',
  'cat id',
  'sub-category',
  'subcategory',
  'product category'
];

export const SHORT_DESCRIPTION_COLUMN_VARIANTS = [
  'short description',
  'shortdescription',
  'summary',
  'brief description',
  'briefdescription',
  'overview',
  'teaser',
  'excerpt',
  'snippet',
  // Added from use-case expansions
  'teaser text',
  'brief',
  'short desc',
  'summary/short description',
  'desc (short)',
  'mini description',
  'highlight',
  'key features'
];

export const STATUS_COLUMN_VARIANTS = [
  'status',
  'state',
  'condition',
  'availability',
  'active',
  'inactive',
  'enabled',
  'disabled',
  // Added from use-case expansions
  'item status',
  'is active',
  'product status',
  'visibility',
  'active/inactive',
  'status (active/inactive)',
  'current status',
  'lifecycle status'
];

export const FEATURED_COLUMN_VARIANTS = [
  'featured',
  'is featured',
  'isfeatured',
  'highlight',
  'featured item',
  'featureditem',
  'starred',
  'promoted',
  'recommended',
  // Added from use-case expansions
  'is promoted',
  'home page featured',
  'featured product',
  'is highlighted',
  'promoted',
  'top product',
  'show on homepage',
  'star product'
];

export const LOW_STOCK_THRESHOLD_COLUMN_VARIANTS = [
  'low stock threshold',
  'lowstockthreshold',
  'reorder level',
  'reorderlevel',
  'min stock',
  'minstock',
  'minimum stock',
  'minimumstock',
  'reorder point',
  'reorderpoint',
  'stock alert',
  'stockalert',
  'alert level',
  'alertlevel',
  // Added from use-case expansions
  'alert threshold',
  're-order point',
  'min qty',
  'minimum order quantity',
  'safety stock level',
  'low inventory alert',
  'restock level',
  'warning level'
];

